name: Build and Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: runner_cnpjInsight

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cnpjinsight-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cnpjinsight-app:latest

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Criar arquivo .env no servidor
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cat > ~/deploy/cnpj_Insight.env <<EOF
          SPRING_DATABASE_HOST=${{ secrets.SPRING_DATABASE_HOST }}
          SPRING_DATABASE_PORT=${{ secrets.SPRING_DATABASE_PORT }}
          SPRING_DATABASE_NAME=${{ secrets.SPRING_DATABASE_NAME }}
          SPRING_DATABASE_USERNAME=${{ secrets.SPRING_DATABASE_USERNAME }}
          SPRING_DATABASE_PASSWORD=${{ secrets.SPRING_DATABASE_PASSWORD }}
          SPRING_DATABASE_SCHEMA=${{ secrets.SPRING_DATABASE_SCHEMA }}
          SPRING_PROFILES_ACTIVE=docker
          SERVER_PORT=8080
          JAVA_OPTS=\"-Xmx1g -Xms512m -XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0\"
          EOF
          "
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd ~/deploy/cnpj_Insight &&
            docker-compose pull &&
            docker-compose down &&
            docker-compose up -d
          "
